async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||"حدث خطأ في الطلب");return body}
const SESSION_KEY="yow_session_id";
const ACCOUNT_KEY="yow_account_id";
const sessionId=()=>sessionStorage.getItem(SESSION_KEY)||"";
const accountId=()=>sessionStorage.getItem(ACCOUNT_KEY)||"";
function setAuth(x){sessionStorage.setItem(SESSION_KEY,x.session_id);sessionStorage.setItem(ACCOUNT_KEY,x.account_id);renderAuth();loadDevices()}
function clearAuth(){sessionStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(ACCOUNT_KEY);renderAuth();loadDevices()}
function renderAuth(){const account=document.querySelector("#account");const status=document.querySelector("#auth-status");if(account)account.value=accountId();if(status)status.textContent=accountId()?"مسجل الدخول • "+accountId():"غير مسجل الدخول"}
document.querySelector('[data-action="health"]').onclick=async()=>{try{document.querySelector('#health').textContent=' جارٍ الفحص...';const x=await api('/health');document.querySelector('#health').textContent=' ✓ '+x.service+' '+x.version}catch(e){document.querySelector('#health').textContent=' ✕ '+e.message}};
document.querySelector('[data-action="register"]').onclick=async()=>{try{const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;if(password.length<12)throw new Error("كلمة المرور يجب أن تكون 12 حرفًا على الأقل");const x=await api("/v1/accounts/register",{method:"POST",body:JSON.stringify({email,password})});document.querySelector("#auth-result").textContent="تم إنشاء الحساب: "+x.account_id;document.querySelector("#email").value="";document.querySelector("#password").value=""}catch(e){document.querySelector("#auth-result").textContent="تعذر إنشاء الحساب: "+e.message}};
document.querySelector('[data-action="login"]').onclick=async()=>{try{const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;const x=await api("/v1/accounts/login",{method:"POST",body:JSON.stringify({email,password})});setAuth(x);document.querySelector("#auth-result").textContent="تم تسجيل الدخول بنجاح."}catch(e){document.querySelector("#auth-result").textContent="تعذر تسجيل الدخول: "+e.message}};
document.querySelector('[data-action="logout"]').onclick=async()=>{const s=sessionId();if(!s)return;try{await api("/v1/accounts/session/revoke?session_id="+encodeURIComponent(s),{method:"POST"})}catch(e){}clearAuth();document.querySelector("#auth-result").textContent="تم تسجيل الخروج."};
async function loadDevices(){const box=document.querySelector('#devices');if(!accountId()||!sessionId()){box.textContent='سجّل الدخول لإدارة أجهزتك.';return}try{const x=await api('/v1/devices?account_id='+encodeURIComponent(accountId()),{headers:{"X-Session-ID":sessionId()}});box.replaceChildren();if(!x.devices.length){box.textContent='لا توجد أجهزة مرتبطة.';return}x.devices.forEach(d=>{const row=document.createElement('div');row.className='device-row';const label=document.createElement('span');label.textContent=d.device_id+' • '+(d.active?'نشط':'ملغى');row.appendChild(label);if(d.active){const revoke=document.createElement('button');revoke.className='ghost';revoke.textContent='إلغاء';revoke.onclick=async()=>{try{await api('/v1/devices/revoke?account_id='+encodeURIComponent(accountId())+'&device_id='+encodeURIComponent(d.device_id),{method:'POST',headers:{"X-Session-ID":sessionId()}});document.querySelector('#result').textContent='تم إلغاء الجهاز.';loadDevices()}catch(e){document.querySelector('#result').textContent='تعذر إلغاء الجهاز: '+e.message}};row.appendChild(revoke)}box.appendChild(row)})}catch(e){box.textContent='تعذر تحميل الأجهزة: '+e.message}}
document.querySelector('[data-action="bind"]').onclick=async()=>{const device=document.querySelector('#device').value.trim(),account=accountId();if(!account||!sessionId()){document.querySelector('#result').textContent='سجّل الدخول أولًا.';return}if(device.length<8){document.querySelector('#result').textContent='أدخل معرّف جهاز صالح.';return}try{await api('/v1/devices/bind',{method:'POST',headers:{"X-Session-ID":sessionId()},body:JSON.stringify({account_id:account,device_id:device,product_id:'yow-core'})});document.querySelector('#result').textContent='تم ربط الجهاز.';loadDevices()}catch(e){document.querySelector('#result').textContent='تعذر ربط الجهاز: '+e.message}};
document.querySelector('[data-action="download"]').onclick=async()=>{const device=document.querySelector('#device').value.trim(),account=accountId();if(!account||!sessionId()){document.querySelector('#result').textContent='سجّل الدخول أولًا.';return}if(device.length<8){document.querySelector('#result').textContent='أدخل معرّف جهاز صالح.';return}try{const q='?account_id='+encodeURIComponent(account)+'&product_id=yow-core&device_id='+encodeURIComponent(device);const x=await api('/v1/download-token'+q,{method:'POST',headers:{"X-Session-ID":sessionId()}});const download=await api('/v1/download'+q,{method:'GET',headers:{"X-Session-ID":sessionId(),"X-Download-Token":x.token}});const link=document.createElement('a');link.href=download.download_url;link.target='_blank';link.rel='noopener';link.textContent='فتح رابط تنزيل آمن';document.querySelector('#result').replaceChildren(link)}catch(e){document.querySelector('#result').textContent='تعذر التنزيل: '+e.message}};

document.querySelector('[data-action="buy"]').onclick=()=>alert('الشراء الحقيقي سيُربط بمزوّد دفع مع webhook موثّق؛ لا توجد عملية دفع وهمية.');
api("/v1/products").then(x=>{document.querySelector("#products").textContent=x.products.map(p=>p.name+" • "+p.version+" • "+p.platform).join("\n")}).catch(()=>{document.querySelector("#products").textContent="تعذر تحميل المنتجات";});
renderAuth();
loadDevices();
