async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||"حدث خطأ في الطلب");return body}
const SESSION_KEY="yow_session_id";
const ACCOUNT_KEY="yow_account_id";
const sessionId=()=>sessionStorage.getItem(SESSION_KEY)||"";
const accountId=()=>sessionStorage.getItem(ACCOUNT_KEY)||"";
function setAuth(x){sessionStorage.setItem(SESSION_KEY,x.session_id);sessionStorage.setItem(ACCOUNT_KEY,x.account_id);renderAuth()}
function clearAuth(){sessionStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(ACCOUNT_KEY);renderAuth()}
function renderAuth(){const account=document.querySelector("#account");const status=document.querySelector("#auth-status");if(account)account.value=accountId();if(status)status.textContent=accountId()?"مسجل الدخول • "+accountId():"غير مسجل الدخول"}
document.querySelector('[data-action="health"]').onclick=async()=>{try{document.querySelector('#health').textContent=' جارٍ الفحص...';const x=await api('/health');document.querySelector('#health').textContent=' ✓ '+x.service+' '+x.version}catch(e){document.querySelector('#health').textContent=' ✕ '+e.message}};
document.querySelector('[data-action="register"]').onclick=async()=>{try{const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;if(password.length<12)throw new Error("كلمة المرور يجب أن تكون 12 حرفًا على الأقل");const x=await api("/v1/accounts/register",{method:"POST",body:JSON.stringify({email,password})});document.querySelector("#auth-result").textContent="تم إنشاء الحساب: "+x.account_id;document.querySelector("#email").value="";document.querySelector("#password").value=""}catch(e){document.querySelector("#auth-result").textContent="تعذر إنشاء الحساب: "+e.message}};
document.querySelector('[data-action="login"]').onclick=async()=>{try{const email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;const x=await api("/v1/accounts/login",{method:"POST",body:JSON.stringify({email,password})});setAuth(x);document.querySelector("#auth-result").textContent="تم تسجيل الدخول بنجاح."}catch(e){document.querySelector("#auth-result").textContent="تعذر تسجيل الدخول: "+e.message}};
document.querySelector('[data-action="logout"]').onclick=async()=>{const s=sessionId();if(!s)return;try{await api("/v1/accounts/session/revoke?session_id="+encodeURIComponent(s),{method:"POST"})}catch(e){}clearAuth();document.querySelector("#auth-result").textContent="تم تسجيل الخروج."};
document.querySelector('[data-action="download"]').onclick=async()=>{const device=document.querySelector('#device').value.trim(),account=accountId();if(!account||!sessionId()){document.querySelector('#result').textContent='سجّل الدخول أولًا.';return}if(device.length<8){document.querySelector('#result').textContent='أدخل معرّف جهاز صالح.';return}try{const q='?account_id='+encodeURIComponent(account)+'&product_id=yow-core&device_id='+encodeURIComponent(device);const x=await api('/v1/download-token'+q,{method:'POST',headers:{"X-Session-ID":sessionId()}});document.querySelector('#result').textContent='تم إصدار رمز تنزيل قصير العمر. مدة الصلاحية: '+x.expires_in+' ثانية\n'+x.token}catch(e){document.querySelector('#result').textContent='تعذر الإصدار: '+e.message}};
document.querySelector('[data-action="buy"]').onclick=()=>alert('الشراء الحقيقي سيُربط بمزوّد دفع مع webhook موثّق؛ لا توجد عملية دفع وهمية.');
api("/v1/products").then(x=>{document.querySelector("#products").textContent=x.products.map(p=>p.name+" • "+p.version+" • "+p.platform).join("\n")}).catch(()=>{document.querySelector("#products").textContent="تعذر تحميل المنتجات";});
renderAuth();
